server:
 port: 8082
spring:
 application:
    name: eureka-server
eureka:
 client:
  service-Url:
   defaultZone: http://localhost:8082/eureka
  register-with-eureka: false
  fetch-registry: false

management:
  endpoints:
    enabled-by-default: true    
 